apiVersion: v2
name: core-dump-handler
description: A Helm chart for deploying a core dump management system to Kubernetes
keywords:
  - coredump
  - post-mortem
  - observability
sources:
  - https://github.com/ibm/core-dump-handler

type: application

version: v9.0.0

appVersion: "v9.0.0"

icon: https://raw.githubusercontent.com/No9/core-dump-handler/master/assets/handle-with-care-svgrepo-com.svg

maintainers:
  - name: No9
    email: anton@venshare.com
    url: https://github.com/No9/
  - name: timbuchwaldt
    email: tim@buchwaldt.ws
    url: https://github.com/timbuchwaldt/
  - name: tjungblu
    email: thomas.jungblut@redhat.com
    url: https://blog.thomasjungblut.com/

annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description:  Add more parameters to helm chart
      links:
        - name: GitHub PR
          url: https://github.com/IBM/core-dump-handler/pull/134
    - kind: fixed
      description: Use error logger in timeout condition
      links:
        - name: GitHub PR
          url: https://github.com/IBM/core-dump-handler/pull/113
    - kind: fixed
      description:  Add service account token secret 
      links:
        - name: GitHub PR
          url: https://github.com/IBM/core-dump-handler/pull/160
  artifacthub.io/images: |
    - name: core-dump-handler
      image: quay.io/icdh/core-dump-handler:v9.0.0
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: BED079E67FD431E45301B1C9949E671B46AC8A34
    url: https://keybase.io/antonwhalley/pgp_keys.asc
