apiVersion: v1
kind: PersistentVolume
metadata:
  name: core-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storageClass }}
{{ if .Values.bindPVThroughClaimRef }}
  claimRef:
    name: core-storage-pvc
    namespace: {{ .Release.Namespace }}
{{ end }}
  capacity:
    storage: {{ .Values.coreStorage }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.daemonset.coreDirectory }}
