apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.coreStorage }}
  storageClassName: {{ .Values.storageClass }}
{{ if not .Values.bindPVThroughClaimRef }}
  volumeName: core-volume
{{ end }}
