apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hostStorage }}
  storageClassName: {{ .Values.storageClass }}
{{ if not .Values.bindPVThroughClaimRef }}
  volumeName: host-volume
{{ end }}
