{{- if .Values.serviceAccount.useToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "core-dump-service-account-token" .Values.serviceAccount.tokenSecretName }}
  annotations:
    kubernetes.io/service-account.name: {{ include "core-dump-handler.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
