{{- if .Values.daemonset.manageStoreSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: s3config
type: Opaque
stringData:
{{- if .Values.daemonset.s3Secret }}
  s3Secret: {{ .Values.daemonset.s3Secret }}
{{- end }}
{{- if .Values.daemonset.s3AccessKey }}
  s3AccessKey: {{ .Values.daemonset.s3AccessKey }}
{{- end }}
{{- if .Values.daemonset.s3BucketName }}
  s3BucketName: {{ .Values.daemonset.s3BucketName }}
{{- end }}
{{- if .Values.daemonset.s3Region }}
  s3Region: {{ .Values.daemonset.s3Region }}
{{- end }}
{{- if .Values.daemonset.azureStorageConnectionString }}
  azureStorageConnectionString: {{ .Values.daemonset.azureStorageConnectionString }}
{{- end }}
{{- if .Values.daemonset.azureStorageAccountName }}
  azureStorageAccountName: {{ .Values.daemonset.azureStorageAccountName }}
{{- end }}
{{- if .Values.daemonset.azureStorageAccountKey }}
  azureStorageAccountKey: {{ .Values.daemonset.azureStorageAccountKey }}
{{- end }}
{{- if .Values.daemonset.azureStorageContainerName }}
  azureStorageContainerName: {{ .Values.daemonset.azureStorageContainerName }}
{{- end }}
{{- if .Values.daemonset.azureStorageBlobEndpoint }}
  azureStorageBlobEndpoint: {{ .Values.daemonset.azureStorageBlobEndpoint }}
{{- end }}
{{- if .Values.daemonset.azureStorageBlobPrefix }}
  azureStorageBlobPrefix: {{ .Values.daemonset.azureStorageBlobPrefix }}
{{- end }}
{{- end }}
